replicaCount: 2

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: latest
serviceAccount:
  create: true
  annotations: {}
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

service:
  type: ClusterIP
  port: 80
